### ISSUE TITLE
QUERY : is it IETF compliant?

### ISSUE THREAD

**Issue by ramrattle** [salrashid123/go_tpm_remote_attestation#1]
Thanks a lot for this open source project, just wanted to know that if the attestation follows IETF RATS or a custom one?

**Comment by salrashid123** [comment]
i'm not 100% sure.  I do think it technically does meet all the specifications (found [this](https://datatracker.ietf.org/doc/draft-ietf-rats-tpm-based-network-device-attest/) link which indicates it does.

a simplified form of this repo adapted for kubernetes is

* https://github.com/salrashid123/tpm_daemonset
* also see https://github.com/google/go-attestation

**Comment by ramrattle** [comment]
ill have a look, thanks a lot
